### ISSUE TITLE
please make me a collaborator on your repository! #1

### ISSUE THREAD

**Issue by fedhere** [EstherNiu/PUI2016_zn352#3]
otherwise I cannot push the citibike reviesion and suggest other changes and improvements.

**Comment by EstherNiu** [comment]
Hi Prof., I've added you as my collaborator. 
Is this collaboration for something I missed during HW4? 
The thing is, I have complete HW4 - submitted my citibike review to my pair's repo, as well as committed other people's pull request into my repo. 
Therefore I don't understand the email you just sent about not having an assigned reviewer?

**Comment by EstherNiu** [comment]
Hi Prof., sorry for the delay. I've added you and TAs as collaborators. 
btw - in case to not occupy your extra effort - I have my assigned citibike review under my repo named CitiBikeReview_tg1478.md
The TA may have trouble locating this review

**Comment by fedhere** [comment]
yes, I could not find it and wrote one CitiBikeReview_fb55.md in your HW3
